"""initial ATS + CRM schema

Revision ID: add53d979437
Revises: 
Create Date: 2026-07-02 14:22:58.100422
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add53d979437'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=True),
    sa.Column('guest_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_activities_guest_id'), ['guest_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_activities_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_activities_user_id'), ['user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('cover_letters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('tone', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('guest_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cover_letters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cover_letters_guest_id'), ['guest_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cover_letters_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cover_letters_user_id'), ['user_id'], unique=False)

    op.create_table('crm_organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=False),
    sa.Column('organization_type', sa.String(length=60), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('email_domain', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('preferred_vendor_status', sa.String(length=60), nullable=True),
    sa.Column('payment_terms', sa.String(length=120), nullable=True),
    sa.Column('contract_status', sa.String(length=60), nullable=True),
    sa.Column('msa_status', sa.String(length=60), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_organizations_email_domain'), ['email_domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_organizations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_organizations_organization_name'), ['organization_name'], unique=False)

    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('middle_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('preferred_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('personal_email', sa.String(length=255), nullable=True),
    sa.Column('company_email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('alternate_phone', sa.String(length=50), nullable=True),
    sa.Column('address_line_1', sa.String(length=255), nullable=True),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=30), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('current_location', sa.String(length=255), nullable=True),
    sa.Column('willing_to_relocate', sa.Boolean(), nullable=True),
    sa.Column('preferred_locations', sa.Text(), nullable=True),
    sa.Column('work_authorization', sa.String(length=120), nullable=True),
    sa.Column('visa_status', sa.String(length=50), nullable=True),
    sa.Column('visa_expiration_date', sa.String(length=30), nullable=True),
    sa.Column('sponsorship_required', sa.Boolean(), nullable=True),
    sa.Column('employment_type', sa.String(length=60), nullable=True),
    sa.Column('current_employer', sa.String(length=255), nullable=True),
    sa.Column('current_job_title', sa.String(length=255), nullable=True),
    sa.Column('primary_skill', sa.String(length=255), nullable=True),
    sa.Column('secondary_skills', sa.Text(), nullable=True),
    sa.Column('total_experience', sa.String(length=50), nullable=True),
    sa.Column('relevant_experience_years', sa.String(length=50), nullable=True),
    sa.Column('availability', sa.String(length=50), nullable=True),
    sa.Column('available_from', sa.String(length=30), nullable=True),
    sa.Column('current_rate', sa.String(length=100), nullable=True),
    sa.Column('expected_rate', sa.String(length=100), nullable=True),
    sa.Column('rate_type', sa.String(length=50), nullable=True),
    sa.Column('remote_preference', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('portfolio_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_employee_code'), ['employee_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_employees_id'), ['id'], unique=False)

    op.create_table('job_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('date_applied', sa.DateTime(), nullable=True),
    sa.Column('job_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('salary_range', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('work_type', sa.String(length=50), nullable=True),
    sa.Column('recruiter_contact', sa.String(length=255), nullable=True),
    sa.Column('recruiter_name', sa.String(length=255), nullable=True),
    sa.Column('recruiter_email', sa.String(length=255), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('reminder_type', sa.String(length=50), nullable=True),
    sa.Column('guest_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_applications_guest_id'), ['guest_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_applications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_applications_user_id'), ['user_id'], unique=False)

    op.create_table('job_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('match_json', sa.Text(), nullable=True),
    sa.Column('guest_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_matches_guest_id'), ['guest_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_matches_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_matches_user_id'), ['user_id'], unique=False)

    op.create_table('job_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('recruiter_name', sa.String(length=255), nullable=True),
    sa.Column('recruiter_email', sa.String(length=255), nullable=True),
    sa.Column('recruiter_phone', sa.String(length=50), nullable=True),
    sa.Column('client', sa.String(length=255), nullable=True),
    sa.Column('end_client', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('work_type', sa.String(length=50), nullable=True),
    sa.Column('rate', sa.String(length=100), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('visa_requirement', sa.String(length=255), nullable=True),
    sa.Column('required_skills', sa.Text(), nullable=True),
    sa.Column('preferred_skills', sa.Text(), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('raw_email_text', sa.Text(), nullable=True),
    sa.Column('submission_deadline', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_requirements_id'), ['id'], unique=False)

    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('headline', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('experience', sa.Text(), nullable=True),
    sa.Column('education', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('portfolio_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profiles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_profiles_user_id'), ['user_id'], unique=True)

    op.create_table('resume_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('ats_score', sa.Float(), nullable=True),
    sa.Column('analysis_json', sa.Text(), nullable=True),
    sa.Column('guest_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_analyses_guest_id'), ['guest_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_analyses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resume_analyses_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('crm_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('normalized_email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('mobile', sa.String(length=50), nullable=True),
    sa.Column('contact_type', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('preferred_contact_method', sa.String(length=60), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=60), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['crm_organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_contacts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_contacts_normalized_email'), ['normalized_email'], unique=True)
        batch_op.create_index(batch_op.f('ix_crm_contacts_organization_id'), ['organization_id'], unique=False)

    op.create_table('employee_resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('storage_provider', sa.String(length=50), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('parsed_name', sa.String(length=255), nullable=True),
    sa.Column('parsed_email', sa.String(length=255), nullable=True),
    sa.Column('parsed_phone', sa.String(length=50), nullable=True),
    sa.Column('parsed_skills', sa.Text(), nullable=True),
    sa.Column('parsed_primary_skill', sa.String(length=255), nullable=True),
    sa.Column('parsed_total_experience', sa.String(length=50), nullable=True),
    sa.Column('parsed_job_titles', sa.Text(), nullable=True),
    sa.Column('parsed_clients', sa.Text(), nullable=True),
    sa.Column('parsed_industries', sa.Text(), nullable=True),
    sa.Column('parsed_certifications', sa.Text(), nullable=True),
    sa.Column('parsed_education', sa.Text(), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee_resumes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_resumes_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_resumes_id'), ['id'], unique=False)

    op.create_table('crm_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=60), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('job_requirement_id', sa.Integer(), nullable=True),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('activity_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['crm_contacts.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['job_requirement_id'], ['job_requirements.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['crm_organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_activities_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_activities_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_activities_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_activities_job_requirement_id'), ['job_requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_activities_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_activities_submission_id'), ['submission_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crm_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_activities_submission_id'))
        batch_op.drop_index(batch_op.f('ix_crm_activities_organization_id'))
        batch_op.drop_index(batch_op.f('ix_crm_activities_job_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_crm_activities_id'))
        batch_op.drop_index(batch_op.f('ix_crm_activities_employee_id'))
        batch_op.drop_index(batch_op.f('ix_crm_activities_contact_id'))

    op.drop_table('crm_activities')
    with op.batch_alter_table('employee_resumes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_resumes_id'))
        batch_op.drop_index(batch_op.f('ix_employee_resumes_employee_id'))

    op.drop_table('employee_resumes')
    with op.batch_alter_table('crm_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_contacts_organization_id'))
        batch_op.drop_index(batch_op.f('ix_crm_contacts_normalized_email'))
        batch_op.drop_index(batch_op.f('ix_crm_contacts_id'))

    op.drop_table('crm_contacts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('resume_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_analyses_user_id'))
        batch_op.drop_index(batch_op.f('ix_resume_analyses_id'))
        batch_op.drop_index(batch_op.f('ix_resume_analyses_guest_id'))

    op.drop_table('resume_analyses')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_profiles_id'))

    op.drop_table('profiles')
    with op.batch_alter_table('job_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_requirements_id'))

    op.drop_table('job_requirements')
    with op.batch_alter_table('job_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_matches_user_id'))
        batch_op.drop_index(batch_op.f('ix_job_matches_id'))
        batch_op.drop_index(batch_op.f('ix_job_matches_guest_id'))

    op.drop_table('job_matches')
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_applications_user_id'))
        batch_op.drop_index(batch_op.f('ix_job_applications_id'))
        batch_op.drop_index(batch_op.f('ix_job_applications_guest_id'))

    op.drop_table('job_applications')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_id'))
        batch_op.drop_index(batch_op.f('ix_employees_employee_code'))
        batch_op.drop_index(batch_op.f('ix_employees_email'))

    op.drop_table('employees')
    with op.batch_alter_table('crm_organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_organizations_organization_name'))
        batch_op.drop_index(batch_op.f('ix_crm_organizations_id'))
        batch_op.drop_index(batch_op.f('ix_crm_organizations_email_domain'))

    op.drop_table('crm_organizations')
    with op.batch_alter_table('cover_letters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cover_letters_user_id'))
        batch_op.drop_index(batch_op.f('ix_cover_letters_id'))
        batch_op.drop_index(batch_op.f('ix_cover_letters_guest_id'))

    op.drop_table('cover_letters')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_type'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('ai_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_activities_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_activities_id'))
        batch_op.drop_index(batch_op.f('ix_ai_activities_guest_id'))

    op.drop_table('ai_activities')
    # ### end Alembic commands ###
