"""add parsing_status and parsed_data to employee_resumes

Revision ID: d25f966bb9c6
Revises: add53d979437
Create Date: 2026-07-02 15:04:58.493801
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd25f966bb9c6'
down_revision: Union[str, None] = 'add53d979437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parsed_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('parsing_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_resumes', schema=None) as batch_op:
        batch_op.drop_column('parsing_status')
        batch_op.drop_column('parsed_data')

    # ### end Alembic commands ###
