import { Document, Packer, Paragraph, TextRun, HeadingLevel } from "docx";
import { jsPDF } from "jspdf";
import type { JobApplication, ResumeAnalysis } from "@/types";

function triggerBlobDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function safeFilenamePart(s: string) {
  return s.trim().replace(/[^a-z0-9]+/gi, "_").replace(/^_+|_+$/g, "") || "untitled";
}

// --- Cover Letter → DOCX ---

export async function downloadCoverLetterDocx(letter: string, companyName?: string, tone?: string) {
  const paragraphs = letter.split(/\n{2,}/).map((block) => {
    const lines = block.split("\n");
    return new Paragraph({
      spacing: { after: 200 },
      children: lines.flatMap((line, i) =>
        i === 0
          ? [new TextRun(line)]
          : [new TextRun({ text: line, break: 1 })]
      ),
    });
  });

  const doc = new Document({
    sections: [
      {
        children: [
          new Paragraph({
            text: companyName ? `Cover Letter — ${companyName}` : "Cover Letter",
            heading: HeadingLevel.HEADING_2,
            spacing: { after: 300 },
          }),
          ...paragraphs,
        ],
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  const name = `cover_letter_${safeFilenamePart(companyName || "company")}${tone ? `_${safeFilenamePart(tone)}` : ""}.docx`;
  triggerBlobDownload(blob, name);
}

// --- Resume Analysis → PDF ---

export function downloadResumeAnalysisPdf(analysis: ResumeAnalysis, filename?: string) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 48;
  const maxWidth = pageWidth - margin * 2;
  let y = margin;

  const ensureSpace = (lines: number, lineHeight: number) => {
    if (y + lines * lineHeight > pageHeight - margin) {
      doc.addPage();
      y = margin;
    }
  };

  const writeHeading = (text: string) => {
    ensureSpace(1, 26);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(30, 27, 75);
    doc.text(text, margin, y);
    y += 20;
    doc.setTextColor(0, 0, 0);
  };

  const writeParagraph = (text: string, opts?: { bullet?: boolean }) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10.5);
    const prefix = opts?.bullet ? "•  " : "";
    const indent = opts?.bullet ? 14 : 0;
    const lines: string[] = doc.splitTextToSize(prefix + text, maxWidth - indent);
    ensureSpace(lines.length, 14);
    doc.text(lines, margin + indent, y);
    y += lines.length * 14 + 4;
  };

  const writeKeyValueRow = (label: string, value: string) => {
    ensureSpace(1, 16);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10.5);
    doc.text(label, margin, y);
    doc.setFont("helvetica", "normal");
    doc.text(value, margin + 130, y);
    y += 16;
  };

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(79, 70, 229);
  doc.text("Resume Analysis Report", margin, y);
  y += 22;
  doc.setTextColor(120, 120, 120);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.text(`Generated by JobLens · ${new Date().toLocaleDateString()}${filename ? ` · ${filename}` : ""}`, margin, y);
  y += 24;
  doc.setTextColor(0, 0, 0);

  writeKeyValueRow("ATS Score:", `${analysis.ats_score}/100`);
  writeKeyValueRow("Formatting Score:", `${analysis.formatting_score}/100`);
  writeKeyValueRow("Content Score:", `${analysis.content_score}/100`);
  y += 10;

  writeHeading("Summary");
  writeParagraph(analysis.overall_summary);
  y += 6;

  writeHeading("Strengths");
  analysis.strengths.forEach((s) => writeParagraph(s, { bullet: true }));
  y += 6;

  writeHeading("Issues Found");
  analysis.weaknesses.forEach((w) => writeParagraph(w, { bullet: true }));
  y += 6;

  writeHeading("Matching Keywords");
  if (analysis.skills_identified.technical.length) {
    writeParagraph(`Technical: ${analysis.skills_identified.technical.join(", ")}`);
  }
  if (analysis.skills_identified.soft.length) {
    writeParagraph(`Soft Skills: ${analysis.skills_identified.soft.join(", ")}`);
  }
  y += 6;

  if (analysis.keywords_missing.length) {
    writeHeading("Missing Keywords");
    writeParagraph(analysis.keywords_missing.join(", "));
    y += 6;
  }

  writeHeading("Recommendations");
  analysis.recommendations.forEach((r) => writeParagraph(`[${r.priority.toUpperCase()}] ${r.suggestion}`, { bullet: true }));

  doc.save(`resume_analysis_${safeFilenamePart(filename?.replace(/\.[^.]+$/, "") || "report")}.pdf`);
}

// --- Job Applications → CSV ---

function csvEscape(value: string): string {
  if (/[",\n]/.test(value)) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}

export function downloadJobsCsv(jobs: JobApplication[]) {
  const columns: { key: keyof JobApplication; label: string }[] = [
    { key: "company", label: "Company" },
    { key: "role", label: "Role" },
    { key: "status", label: "Status" },
    { key: "date_applied", label: "Date Applied" },
    { key: "location", label: "Location" },
    { key: "work_type", label: "Work Type" },
    { key: "salary_range", label: "Salary Range" },
    { key: "job_url", label: "Job URL" },
    { key: "recruiter_contact", label: "Recruiter Contact" },
    { key: "follow_up_date", label: "Follow-up Date" },
    { key: "reminder_type", label: "Reminder Type" },
    { key: "notes", label: "Notes" },
  ];

  const header = columns.map((c) => csvEscape(c.label)).join(",");
  const rows = jobs.map((job) =>
    columns
      .map((c) => {
        const raw = job[c.key];
        return csvEscape(raw == null ? "" : String(raw));
      })
      .join(",")
  );

  const csv = [header, ...rows].join("\r\n");
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  triggerBlobDownload(blob, `joblens_applications_${new Date().toISOString().slice(0, 10)}.csv`);
}
